backend:
  name: git-gateway
  branch: master

media_folder: "public/content"
public_folder: "content/"

collections:
  - name: education
    label: Education
    widget: list
    fields:
      - {label: Institution, name: institution, widget: string}
      - {label: Start date, name: startDate, widget: date}
      - {label: End date, name: endDate, widget: date, required: false}
      - {label: Qualifications, name: qualifications, widget: string}
