backend:
  name: github
  repo: jonlinnell/jonlinnell.co.uk

media_folder: "public/content"
public_folder: "content/"

collections:
  - label: "CV"
    name: "cv"
    files:
    - label: "Basics"
      name: "basics"
      file: "public/content/cv/basics.yml"
      fields:
        - {label: Name, name: name, widget: string}
        - {label: Strapline, name: strapline, widget: string}
