backend:
  name: github
  repo: jonlinnell/jonlinnell.co.uk

media_folder: "public/content"
public_folder: "content/"

collections:
  - label: CV
    name: cv
    editor:
    - preview: false
    files:
    - label: Basics
      name: basics
      file: "public/content/cv/basics.json"
      format: json
      fields:
        - {label: Name, name: name, widget: string}
        - {label: Strapline, name: strapline, widget: string}
    - name: contact
      label: Contact
      file: contact.json
      format: json
      fields:
        - name: contact
          label: Contact Information,
          widget: list,
          fields:
            - { label: Platform, name: platform, widget: select, options: ["Phone", "Website", "Facebook", "Twitter", "Linkedin", "Instagram", "GitHub"] }
            - { label: Description, name: description, widget: string }
    - name: skills
      label: Skills
      file: public/content/cv/skills.json
      format: json
      widget: list
      fields:
        - name: 'skills'
          label: Skills
          widget: list
          fields:
            - { label: Skill, name: skill, widget: string }
            - { label: Descriptions, name: description, widget: text }
    - name: summary
      label: Summary
      file: public/content/cv/summary.json
      format: json
      fields:
        - { label: Column 1, name: col1, widget: text }
        - { label: Column 2, name: col2, widget: text }
        - { label: Column 3, name: col3, widget: text }
    - name: education
      label: Education
      file: public/content/cv/education.json
      format: json
      widget: list
      fields:
        - { label: Institution, name: institution, widget: string }
        - { label: Start date, name: startDate, widget: date }
        - { label: End date, name: endDate, widget: date, required: false }
        - { label: Qualifications, name: qualifications, widget: string }
    - name: employment
      label: Employment
      file: public/content/cv/employment.json
      format: json
      widget: list
      fields:
        - { label: Organisation, name: organisation, widget: string }
        - { label: Start date, name: startDate, widget: date }
        - { label: End date, name: endDate, widget: date, required: false }
        - { label: Post, name: post, widget: string }
        - { label: Description, name: description, widget: text, required: false }

